[package]
name = "bereshit-l3-types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
bereshit-l0-foundation = { workspace = true }

[lints]
workspace = true
