/**
 * @file example_01_minimal.c
 * @brief Minimal OmniCode example - adds two numbers
 *
 * GENERATED FROM: example_01_minimal.omni
 * KEY: EXAMPLE-01-MINIMAL
 * VERSION: a-01.00
 *
 * This file was generated by the OmniCode transpiler.
 * Do not edit directly - modify the .omni source instead.
 */

// ============================================================================
// SETUP
// ============================================================================

#include <stdint.h>

// ============================================================================
// BODY
// ============================================================================

/**
 * @brief Add two numbers together.
 * @param a First number
 * @param b Second number
 * @return Sum of a and b
 */
int32_t add_numbers(int32_t a, int32_t b) {
    return a + b;
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
